CREATE TABLE TODO_ITEM (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    PRIORITY INTEGER NOT NULL CHECK (("PRIORITY" <= 4) AND ("PRIORITY" >= 1)),
    DONE BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);